name: yandex_gpt_rest_sdk
description: A new Flutter project.
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  http: ^1.1.0
dev_dependencies:
  lint: ^2.1.1