name: yandex_gpt_rest_api
description: A library for using YandexGPT API, such as generating text and obtain embeddings.
version: 1.0.2
homepage: https://github.com/vladcto/yandex-gpt-rest-api
repository: https://github.com/vladcto/yandex-gpt-rest-api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.8
  http_mock_adapter: ^0.6.1
  lint: ^2.3.0
  mockito: ^5.4.4
  test: ^1.25.1
