name: yandex_gpt_rest_api
description: Dart package for calling the Foundation Models RESTfull API.
version: 0.4.0
homepage: https://github.com/vladcto/yandex-gpt-rest-sdk
repository: https://github.com/vladcto/yandex-gpt-rest-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  http_mock_adapter: ^0.6.1
  lint: ^2.2.0
  mockito: ^5.4.0
  test: ^1.24.0
