name: yandex_gpt_rest_api
description: Communicating with the Yandex Foundation Models API.
version: 0.3.5
homepage: https://github.com/vladcto/yandex-gpt-rest-sdk
repository: https://github.com/vladcto/yandex-gpt-rest-sdk

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  http: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.7
  lint: ^2.1.1
  mockito: ^5.4.3
  test: ^1.24.3
