name: yandex_gpt_rest_api
description: yandex_gpt_rest_api
version: 0.2.0
homepage: https://github.com/vladcto/yandex-gpt-rest-sdk
repository: https://github.com/vladcto/yandex-gpt-rest-sdk

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  async: ^2.11.0
  http: ^1.1.0
dev_dependencies:
  lint: ^2.1.1
  test: ^1.24.3