name: Dart check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v9a04e6d73cca37bd455e0608d7e5092f881fd603

      - uses: dart-lang/setup-dart@v1

      - name: Check version
        run: dart --version
      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test