name: Format and Analyze

on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/setup_repo_with_dart.yaml

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/setup_repo_with_dart.yaml

      - name: Analyze project source
        run: dart analyze --fatal-infos