name: Format and Analyze

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze project source
        if: '!cancelled()'
        run: dart analyze --fatal-infos